### ISSUE TITLE
Normal uninstalling HidHide disabled ALL of my USB devices

### ISSUE THREAD

**Issue by LeCoyote** [nefarius/HidHide#131] opened 2024-01-16 15:39 UTC
### Bug description

Went to Windows "Add/remove programs" and uninstalled HidHide. When prompted, rebooted the computer. There was ***NO*** attempt at a forced removal whatsoever.

On subsequent start, all USB HID devices stopped working. Had to go to system repair to restore normal use of my peripherals.

### Machine info
Windows 10 22H2 on x64 (Intel), HidHide 1.4.192

**Comment by CasperH2O** [comment] 2024-01-18 11:47
Today a user of the HC application also installed HidHide directly, resulting in the same situation. However, after recovering thanks to the instructions, another two attempts at uninstalling did not lead to the same result.

**Comment by nefarius** [comment] 2024-01-18 13:08
It does if you instruct it to (optional CLI argument). I have not received a single log for analysis yet.

**Comment by CasperH2O** [comment] 2024-01-18 14:42
@nefarius my apologies, I think I did not formulate my question correctly.

What I meant to ask is, if I install HidHide and then uninstall only HidHide through the Windows remove programs interface, does HidHide create any logfile of the uninstallation process?

I am still working on trying to get a logfile when HC uninstalls HH, I have a special build of HC with the additional CLI arguments but thus far no one has come forth who can reproduce the issue consistently.

**Comment by nefarius** [comment] 2024-01-18 14:55
> What I meant to ask is, if I install HidHide and then uninstall only HidHide through the Windows remove programs interface, does HidHide create any logfile of the uninstallation process?

I see. No it does not, `msiexec` needs to be instructed to do so via CLI arguments.

**Comment by nefarius** [comment] 2024-02-04 14:41
Fixed in latest release.

**Closed by nefarius** 2024-02-04 14:41 UTC

**Comment by ThomasMeisters** [comment] 2024-02-04 16:50
Same thing happened to me after updating. It briefly gave an error about something not being installed properly, but that promptly went away since I just choose the option to restart my PC after installing the update. Now I cannot use any USB device so I’m essentially softlocked. How did you resolve this @LeCoyote ?

**Comment by nefarius** [comment] 2024-02-04 16:54
> Same thing happened to me after updating. It briefly gave an error about something not being installed properly, but that promptly went away since I just choose the option to restart my PC after installing the update. Now I cannot use any USB device so I’m essentially softlocked. How did you resolve this @LeCoyote ?

Since the fault is in the **uninstaller**, ofc. removing the older version can still trigger this problem, the latest release is fixed, it can not retroactively fix a faulty uninstall. There's a guide linked on the release page on how to recover from this problem.

**Comment by ThomasMeisters** [comment] 2024-02-04 17:06
I was able to fix it using that guide, thanks!

**Comment by LeCoyote** [comment] 2024-02-05 14:54
@ThomasMeisters I booted into system rescue and restored a system backup, I wanted a foolproof solution :)

**Comment by nefarius** [comment] 2024-02-05 14:59
If you really value your PC and data you'll have a backup anyway 😇

**Comment by LeCoyote** [comment] 2024-02-05 15:04
Um yeah, that's already taken care off, I'd just never come across a software that could brick a system upon uninstallation, is all. Lesson learned, but thanks for the "tip".

**Comment by nefarius** [comment] 2024-02-05 15:07
I have Software for every use-case, no matter how obscure!

**Comment by TrantaLocked** [comment] 2024-05-27 13:56
Where is the guide? Anything I do to fix this will have to be done in recovery environment.

**Comment by nefarius** [comment] 2024-05-27 14:41
Literally linked above already...
