### ISSUE TITLE
Update installer fails if you click on the button to not immediately reboot in the actual installer

### ISSUE THREAD

**Issue by Filoppi** [nefarius/HidHide#138] opened 2024-02-08 10:45 UTC
This happened twice recently, both times that HidHide tried to auto update.
<img width="429" alt="HidHide_Updater_uIjhf603bg" src="https://github.com/nefarius/HidHide/assets/7011366/3cb43e28-642e-4e25-9e07-63ca33e8d949">
after restarting, I think I then had to re-do the installation from scratch, I'm not sure if underneath the program installation/update was actually successful or not.

**Comment by nefarius** [comment] 2024-02-08 12:54
Duplicate of #110

**Closed by nefarius** 2024-02-08 12:54 UTC
